
42,0.5,lfr,dpctgan,"Invalid classes inferred from unique values of `y`.  Expected: [0], got [1.]","['  File ""/home/vangeloz/public/Experiments/src/utils/benchmark.py"", line 152, in run\n    self.results.append(pre_mitigator_experiment(X_train, y_train, X_cal, y_cal, X_test, y_test, mitigator, self.seed, self.normalize, self.threshold))\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 177, in pre_mitigator_experiment\n    raise e\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 172, in pre_mitigator_experiment\n    mitigator_model.fit(X_train_transf, y_train_transf, sample_weight=mitigated_train_weights)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/core.py"", line 726, in inner_f\n    return func(**kwargs)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/sklearn.py"", line 1491, in fit\n    raise ValueError(\n']"
42,0.5,lfr,dpctgan,"Invalid classes inferred from unique values of `y`.  Expected: [0], got [1.]","['  File ""/home/vangeloz/public/Experiments/src/utils/benchmark.py"", line 152, in run\n    self.results.append(pre_mitigator_experiment(X_train, y_train, X_cal, y_cal, X_test, y_test, mitigator, self.seed, self.normalize, self.threshold))\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 177, in pre_mitigator_experiment\n    raise e\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 172, in pre_mitigator_experiment\n    mitigator_model.fit(X_train_transf, y_train_transf, sample_weight=mitigated_train_weights)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/core.py"", line 726, in inner_f\n    return func(**kwargs)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/sklearn.py"", line 1491, in fit\n    raise ValueError(\n']"
42,0.5,lfr,dpctgan,"Invalid classes inferred from unique values of `y`.  Expected: [0], got [1.]","['  File ""/home/vangeloz/public/Experiments/src/utils/benchmark.py"", line 152, in run\n    self.results.append(pre_mitigator_experiment(X_train, y_train, X_cal, y_cal, X_test, y_test, mitigator, self.seed, self.normalize, self.threshold))\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 177, in pre_mitigator_experiment\n    raise e\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 172, in pre_mitigator_experiment\n    mitigator_model.fit(X_train_transf, y_train_transf, sample_weight=mitigated_train_weights)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/core.py"", line 726, in inner_f\n    return func(**kwargs)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/sklearn.py"", line 1491, in fit\n    raise ValueError(\n']"
42,0.5,lfr,dpctgan,"Invalid classes inferred from unique values of `y`.  Expected: [0], got [1.]","['  File ""/home/vangeloz/public/Experiments/src/utils/benchmark.py"", line 152, in run\n    self.results.append(pre_mitigator_experiment(X_train, y_train, X_cal, y_cal, X_test, y_test, mitigator, self.seed, self.normalize, self.threshold))\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 177, in pre_mitigator_experiment\n    raise e\n', '  File ""/home/vangeloz/public/Experiments/src/utils/pre.py"", line 172, in pre_mitigator_experiment\n    mitigator_model.fit(X_train_transf, y_train_transf, sample_weight=mitigated_train_weights)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/core.py"", line 726, in inner_f\n    return func(**kwargs)\n', '  File ""/home/vangeloz/public/Experiments/exp_venv/lib/python3.9/site-packages/xgboost/sklearn.py"", line 1491, in fit\n    raise ValueError(\n']"
